name: Quickstart CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: '[DEBUG] Echo environment variables'
        run: 'gci Env:'
        shell: pwsh

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: '[WORKAROUND] Fetch required tags for GitVersion'
        run: |
          git fetch --tags
          git branch --create-reflog master origin/master

      - name: '[WORKAROUND] Get branch name'
        id: get_branch_name
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/get-branch-name@master

      - name: Validate & detect quickstart solution changes
        id: validate_and_detect_qs_changes
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/validate-and-detect-quickstart-changes@master
        with:
          repo_name: ${{ github.repository }}
          trigger: ${{ github.event_name }}
          pr_number: ${{ github.event.number }}
          source_version: ${{ github.sha }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Authenticate against Azure Container Registry (docker registry)
        uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: ${{ secrets.REGISTRY_SERVER }}
      
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Calculate quickstart solution version from Porter manifest, using GitVersion
        id: calculate_version
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/calculate-version@master
        with:
          manifest_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/porter.yaml

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Install latest version of Porter
        id: install_porter
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/install-porter@master
        with:
          porter-version: v0.17.1-beta.1

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Patch version and registry for bundle and invocation image
        id: replace_version_and_registry
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/replace-version-and-registry@master
        with:
          manifest_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/porter.yaml
          version: ${{ steps.calculate_version.outputs.nuget_version_v2 }}
          tag: ${{ steps.calculate_version.outputs.nuget_version_v2 }}
          registry: ${{ secrets.REGISTRY_SERVER }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Build Porter bundle
        id: build_porter_bundle
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/build-porter-bundle@master
        with:
          bundle_dir: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Publish Porter bundle and invocation image
        id: publish_porter_bundle
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/publish-porter-bundle@master
        with:
          bundle_dir: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter' && github.event_name == 'push'
        name: Patch bundle and invocation image tags with 'latest'
        id: replace_tag_with_latest
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/replace-version-and-registry@master
        with:
          manifest_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/porter.yaml
          version: ${{ steps.calculate_version.outputs.nuget_version_v2 }}
          tag: 'latest'
          registry: ${{ secrets.REGISTRY_SERVER }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter' && github.event_name == 'push'
        name: Publish 'latest' Porter bundle and invocation image
        id: publish_latest_porter_bundle
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/publish-porter-bundle@master
        with:
          bundle_dir: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}
          
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Generate ARM template for 'Deploy to Azure' button
        id: generate_arm_template
        uses: endjin/CNAB.ARM-Converter.GitHub.Actions/run-cnab-to-arm-tool@master
        with:
          bundle_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/.cnab/bundle.json
          output_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/azuredeploy.json
          
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Generate quickstart solution readme
        id: generate_readme
        uses: endjin/CNAB.ARM-Converter.GitHub.Actions/generate-readme@master
        with:
          bundle_metadata_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/.cnab/bundle.json
          instructions_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/INSTRUCTIONS.md
          template_uri: https://raw.githubusercontent.com/${{ github.repository }}/${{ steps.get_branch_name.outputs.branch_name }}/${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/azuredeploy.json
          output_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/README.md

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Commit & push ARM template & readme (if updated)
        uses: endjin/git-auto-commit-action@master
        with:
          add_path_spec: '${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/README.md ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/azuredeploy.json'
          commit_message: "Update ARM template / readme for bundle '${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}'"
          branch: ${{ steps.get_branch_name.outputs.branch_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
